import type { Metadata } from 'next';
import LegalLayout from '@/components/legal/LegalLayout';

export const metadata: Metadata = {
  title: "Privacy Policy | Spin'A'Cloud™",
  description: "Spin'A'Cloud™ is committed to protecting your personal information. This Privacy Policy explains what data we collect, how we use it, and your rights under the Digital Personal Data Protection Act 2023 (DPDPA).",
  alternates: {
    canonical: '/privacy-policy',
  },
  openGraph: {
    title: "Privacy Policy | Spin'A'Cloud™",
    description: "Spin'A'Cloud™ is committed to protecting your personal information. This Privacy Policy explains what data we collect, how we use it, and your rights under the DPDPA 2023.",
    url: 'https://spinacloud.in/privacy-policy',
  },
};

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout
      badge="Data Protection"
      title="Privacy Policy"
      dateInfo="Effective date: 1 July 2025 | Last updated: 1 July 2025"
    >
      {/* Intro Callout Box */}
      <div className="p-4 sm:p-5 rounded-xl border border-[#FF6600]/40 bg-[#FF6600]/5 text-neutral-200 text-sm sm:text-base leading-relaxed">
        Spin'A'Cloud™ is committed to protecting your personal information. This Privacy Policy explains
        what data we collect, how we use it, and your rights under the Digital Personal Data Protection
        Act 2023 (DPDPA) and other applicable Indian laws.
      </div>

      {/* 1. Who We Are */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          1. Who We Are
        </h2>
        <p>
          Spin'A'Cloud™ is operated by Shirish Productions (operating as Spin'A'Cloud™), based in Belgaum
          (Belagavi), Karnataka, India. We act as the Data Fiduciary in respect of personal data
          collected through our website and Portal. For privacy-related queries, contact our designated
          Privacy Contact at{' '}
          <a href="mailto:privacy@spinacloud.in" className="text-primary hover:underline">
            privacy@spinacloud.in
          </a>
          .
        </p>
      </section>

      {/* 2. What Personal Data We Collect */}
      <section className="space-y-4">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          2. What Personal Data We Collect
        </h2>

        <div className="space-y-2">
          <h3 className="text-base font-semibold font-inter text-[#FF6600]">
            2.1 Data You Provide Directly
          </h3>
          <ul className="list-disc pl-6 space-y-2 text-neutral-300">
            <li>
              <strong className="text-white">Account registration:</strong> full name, email address, phone number, and password.
            </li>
            <li>
              <strong className="text-white">Billing information:</strong> name, GST number, billing address, and payment method details (processed via our PCI-DSS compliant payment gateway; we do not store full card numbers).
            </li>
            <li>
              <strong className="text-white">Support queries:</strong> any information you include in communications with our support team.
            </li>
            <li>
              <strong className="text-white">KYC information:</strong> if required for regulatory compliance, identity documentation.
            </li>
          </ul>
        </div>

        <div className="space-y-2">
          <h3 className="text-base font-semibold font-inter text-[#FF6600]">
            2.2 Data Collected Automatically
          </h3>
          <ul className="list-disc pl-6 space-y-2 text-neutral-300">
            <li>
              <strong className="text-white">Usage data:</strong> pages visited on our website and Portal, features used, time and duration of sessions.
            </li>
            <li>
              <strong className="text-white">Technical data:</strong> IP address, browser type and version, device type, operating system, and referring URLs.
            </li>
            <li>
              <strong className="text-white">Server logs:</strong> access logs generated by your use of hosted services on our infrastructure.
            </li>
            <li>
              <strong className="text-white">Cookies and similar technologies:</strong> as described in our Cookie Policy.
            </li>
          </ul>
        </div>

        <div className="space-y-2">
          <h3 className="text-base font-semibold font-inter text-[#FF6600]">
            2.3 Data From Third Parties
          </h3>
          <p>
            We may receive limited personal data from payment gateways (transaction status, masked card
            details) and from identity verification services where applicable.
          </p>
        </div>
      </section>

      {/* 3. How We Use Your Personal Data */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          3. How We Use Your Personal Data
        </h2>
        <p>
          We use your personal data for the following purposes and on the following legal bases:
        </p>
        <ul className="list-disc pl-6 space-y-2 text-neutral-300">
          <li>
            Providing and managing your account and Services - necessary for the performance of your
            contract with us.
          </li>
          <li>
            Processing payments and issuing invoices - necessary for contractual performance and legal
            compliance (GST obligations under Indian tax law).
          </li>
          <li>
            Sending transactional communications (account confirmations, payment receipts, service
            alerts, maintenance notifications) - necessary for contractual performance.
          </li>
          <li>
            Sending marketing communications about new features, plans, or offers - based on your
            consent, which you may withdraw at any time by clicking &apos;Unsubscribe&apos; in any email.
          </li>
          <li>
            Improving our services through usage analytics - based on our legitimate interest in
            providing a better service.
          </li>
          <li>
            Complying with legal obligations, responding to lawful requests from government or
            regulatory authorities.
          </li>
          <li>
            Detecting, preventing, and responding to fraud, security incidents, and abuse.
          </li>
        </ul>
      </section>

      {/* 4. Data Storage and Security */}
      <section className="space-y-4">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          4. Data Storage and Security
        </h2>

        <div className="space-y-2">
          <h3 className="text-base font-semibold font-inter text-[#FF6600]">
            4.1 Storage Location
          </h3>
          <p>
            Your personal data and the content you host on Spin'A'Cloud™ is stored in data centres located
            within India (IXG-Belagavi zone). We do not transfer your personal data outside India except
            where strictly necessary for payment processing or legal compliance, and in such cases we
            ensure adequate protections are in place.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-base font-semibold font-inter text-[#FF6600]">
            4.2 Security Measures
          </h3>
          <p>
            We implement appropriate technical and organisational measures to protect your personal
            data, including SSL/TLS encryption in transit, encrypted storage for sensitive data, access
            controls limiting data access to authorised personnel only, regular security assessments, and
            DDoS protection infrastructure.
          </p>
        </div>

        <div className="space-y-2">
          <h3 className="text-base font-semibold font-inter text-[#FF6600]">
            4.3 Data Breach
          </h3>
          <p>
            In the event of a personal data breach that is likely to result in risk to your rights and
            freedoms, we will notify you and the relevant authorities as required under applicable Indian
            law, including the DPDPA.
          </p>
        </div>
      </section>

      {/* 5. How Long We Keep Your Data */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          5. How Long We Keep Your Data
        </h2>
        <ul className="list-disc pl-6 space-y-2 text-neutral-300">
          <li>
            <strong className="text-white">Account data:</strong> retained for the duration of your account and for 3 years after account closure, for legal and dispute resolution purposes.
          </li>
          <li>
            <strong className="text-white">Billing and invoicing records:</strong> retained for 8 years to comply with Indian accounting and tax law (Companies Act 2013, GST law).
          </li>
          <li>
            <strong className="text-white">Server logs:</strong> retained for up to 90 days.
          </li>
          <li>
            <strong className="text-white">Support communications:</strong> retained for 2 years after the resolution of the query.
          </li>
          <li>
            <strong className="text-white">Marketing consent records:</strong> retained until you withdraw consent plus 3 years.
          </li>
        </ul>
        <p>When data is no longer required, we delete it securely or anonymise it.</p>
      </section>

      {/* 6. Sharing Your Personal Data */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          6. Sharing Your Personal Data
        </h2>
        <p>We do not sell your personal data. We share it only in the following circumstances:</p>
        <ul className="list-disc pl-6 space-y-2 text-neutral-300">
          <li>
            <strong className="text-white">Service providers:</strong> third parties who help us deliver services (payment gateways such as Razorpay, infrastructure providers, email delivery services). These parties are bound by data processing agreements and may only process your data for the purposes we specify.
          </li>
          <li>
            <strong className="text-white">Legal compliance:</strong> where required by Indian law, court order, or government authority.
          </li>
          <li>
            <strong className="text-white">Business transfers:</strong> in the event of a merger, acquisition, or sale of our business, your data may be transferred to the successor entity, subject to equivalent privacy protections.
          </li>
          <li>
            <strong className="text-white">With your consent:</strong> for any other purpose you explicitly agree to.
          </li>
        </ul>
      </section>

      {/* 7. Your Rights Under the DPDPA */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          7. Your Rights Under the DPDPA
        </h2>
        <p>Under the Digital Personal Data Protection Act 2023, you have the following rights:</p>
        <ul className="list-disc pl-6 space-y-2 text-neutral-300">
          <li>
            <strong className="text-white">Right to access:</strong> you can request details of the personal data we hold about you.
          </li>
          <li>
            <strong className="text-white">Right to correction:</strong> you can request that we correct inaccurate or incomplete data.
          </li>
          <li>
            <strong className="text-white">Right to erasure:</strong> you can request deletion of your personal data, subject to our legal obligations to retain certain records.
          </li>
          <li>
            <strong className="text-white">Right to withdraw consent:</strong> where processing is based on consent, you may withdraw it at any time without affecting the lawfulness of prior processing.
          </li>
          <li>
            <strong className="text-white">Right to grievance redressal:</strong> you have the right to raise a grievance with us, which we will address within 30 days.
          </li>
        </ul>
        <p>
          To exercise any of these rights, contact us at{' '}
          <a href="mailto:privacy@spinacloud.in" className="text-primary hover:underline">
            privacy@spinacloud.in
          </a>
          . We may need to verify your identity before processing your request.
        </p>
      </section>

      {/* 8. Children's Privacy */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          8. Children&apos;s Privacy
        </h2>
        <p>
          Spin'A'Cloud™&apos;s services are intended for individuals aged 18 and over. We do not knowingly
          collect personal data from anyone under 18. If you believe we have inadvertently collected
          data from a minor, please contact us at{' '}
          <a href="mailto:privacy@spinacloud.in" className="text-primary hover:underline">
            privacy@spinacloud.in
          </a>{' '}
          and we will delete it promptly.
        </p>
      </section>

      {/* 9. Third-Party Links */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          9. Third-Party Links
        </h2>
        <p>
          Our website may contain links to third-party websites. We are not responsible for the privacy
          practices of those websites and encourage you to review their privacy policies before
          providing any personal data.
        </p>
      </section>

      {/* 10. Changes to This Privacy Policy */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          10. Changes to This Privacy Policy
        </h2>
        <p>
          We may update this Privacy Policy from time to time. The updated version will be posted on
          our website with a revised effective date. For material changes, we will notify you by email.
          Your continued use of our Services after the effective date constitutes acceptance of the
          revised Policy.
        </p>
      </section>

      {/* 11. Contact and Grievance Officer */}
      <section className="space-y-3">
        <h2 className="text-lg sm:text-xl font-bold font-inter text-white">
          11. Contact and Grievance Officer
        </h2>
        <p>
          If you have any questions, concerns, or complaints about how we handle your personal data,
          please contact:
        </p>
        <div className="p-4 rounded-xl bg-white/[0.03] border border-white/10 space-y-1.5 text-sm text-neutral-300">
          <p className="font-bold text-white">Privacy Contact / Grievance Officer — Spin'A'Cloud™</p>
          <p className="text-neutral-400">Shirish Productions (operating as Spin'A'Cloud™)</p>
          <p>
            <span className="text-neutral-400">Address:</span> CTS No. 3439/1A and 3439/2A, 4th Floor, MORE Plaza, College Road, Above Arena Animation Belagavi, Karnataka – 590001
          </p>
          <p>
            <span className="text-neutral-400">Phone:</span>{' '}
            <a href="tel:+918105631983" className="text-primary hover:underline">
              +91 810-5631-983
            </a>
          </p>
          <p>
            <span className="text-neutral-400">Email:</span>{' '}
            <a href="mailto:mail@spinacloud.com" className="text-primary hover:underline">
              mail@spinacloud.com
            </a>
          </p>
        </div>
        <p className="text-sm text-neutral-400 pt-1">
          We will acknowledge your query within 48 hours and resolve it within 30 days.
        </p>
      </section>
    </LegalLayout>
  );
}
